### ISSUE TITLE
fix: Calling 'mason make r13n' fails when mason templates exist

### ISSUE THREAD

**Issue by b-nugent** [VeryGoodOpenSource/r13n#33]
**Description**
Hello! I'm currently trying to incorporate r13n into an existing project. When I run `mason make r13n --on-conflict overwrite` it fails during the step when it runs `flutter format .` due to the project having existing mason templates. The r13n generated files (app_regionalizations_us.g.dart, etc) are created but the formatting part of it fails. I'm wondering if it's possible for r13n's mason command to make a more localized flutter format call instead?

**Steps To Reproduce**

1. Install mason and make a template (under `project-directory/mason/`)
2. Install r13n and run the `mason make r13n --on-conflict overwrite` command

**Expected Behavior**
The r13n files should be created under `project-directory/lib/r13n/` and flutter formatting should be run on them successfully.

**Comment by alestiago** [comment]
Hi, sorry for the late reply due to the Christmas break.

I've haven't attempted yet to reproduce the issue, however does skipping the formatting entirely avoid the failure? I've created a fork where the formatter is skipped during the post hook (https://github.com/alestiago/r13n/commits/fix/flutter-format-i33).

```yaml
dependency_overrides:
  r13n:
    git:
      url: https://github.com/alestiago/r13n
      path: r13n
      ref: 66946c55425f8514c1636baef3978b7da19c5bea
```

> I'm wondering if it's possible for r13n's mason command to make a more localized flutter format call instead?
I agree that `r13n` should only attempt to `format` the generated files only. In addition to this perhaps a configuration parameter can be added to the r13n.yaml to specify if the formatter should run or not. Wdyt?

**Comment by b-nugent** [comment]
Hey Alejandro!
I pulled in that fork as a dependency but am noticing the r13n brick runs through the same formatting step instead of skipping it. I removed and re-added the brick after pulling in the dep but it continues to operate as previously. Maybe I'm missing something?

 I think adding a parameter to skip the formatting step could work, thanks for taking a look into this!
